version: '3.8'

services:
  # 1. Servicio de Base de Datos (MySQL)
  db:
    image: mysql:8.0
    container_name: runtime-db
    restart: always
    environment:
      MYSQL_DATABASE: runtime_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306" # Mapeamos el puerto al localhost
    volumes:
      - mysql_data:/var/lib/mysql # Persistencia de datos (para no perderlos al apagar)

  # 2. Servicio de phpMyAdmin (Interfaz visual)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: runtime-pma
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  mysql_data: