version: '3.8'

services:
  # bd
  db:
    image: mysql:8.0
    container_name: runtime-db
    restart: always
    environment:
      MYSQL_DATABASE: runtime_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      # puerto_pc:puerto_contenedor
      - "3306:3306" # Mapeamos el puerto al localhost
    volumes:
      - mysql_data:/var/lib/mysql # Persistencia de datos (para no perderlos al apagar)
  # bd para testing
  db_test:
    image: mysql:8.0
    container_name: runtime-db-test
    restart: always
    environment:
      MYSQL_DATABASE: runtime_test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: runtime-pma
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  mysql_data: